version: "3.7"
services:
  app:
    image: mi-app:latest
    networks:
      - admin
    environment:
      - TZ=America/Mexico_City
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.role == manager
      restart_policy:
        condition: on-failure
        max_attempts: 3
      labels:
        - traefik.enable=true
        - traefik.http.routers.miapp.rule=Host(`tudominio.com`)
        - traefik.http.routers.miapp.entrypoints=web,websecure
        - traefik.http.routers.miapp.tls=true
        - traefik.http.routers.miapp.tls.certresolver=letsencryptresolver
        - traefik.http.services.miapp.loadbalancer.server.port=80
        - traefik.http.routers.miapp.service=miapp

networks:
  admin:
    external: true
    name: admin